name: Build Release App Bundle

on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Copy the keystore file to the app root
        run: mkdir app/keystore && cp /home/runner/work/_temp/keystore/keystore.jks app/keystore/
      - name: Grant execute permission for gradlew 
        run: chmod +x gradlew
      - name: build prod
        run: ./gradlew app:build && mv app/build/outputs/apk/release/*.apk vitabu-signed.apk
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: vitabu-signed.apk

  release:
    name: Release APK
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v2
        with:
          name: release-apk  
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          name: Release ${{ github.ref_name }} 
          files: vitabu-signed.apk
